

PORT  = 12345
HOSTS = localhost #vkajdslm

actionset1: #potato
	echo starting actionset1
	cal
		requires client-c.c potato.c
	remote-cal
		requires client-c.c potato.c
	remote-cc program.c # potato
		requires program.c program.h allfunctions.h # potato
