# A typical Rakefile

PORT  = 12345
HOSTS = localhost:12345

actionset1:
	echo starting actionset1
	cal
	cc -c program.c
		requires program.c program.h allfunctions.h
	cc -c square.c
		requires square.c allfunctions.h
	cc -c cube.c
		requires cube.c allfunctions.h
	

actionset2:
	echo starting actionset2
	cc -o program program.o square.o cube.o
		requires program.o square.o cube.o

actionset3:
	echo starting actionset3
	remote-echo dabbing
	remote-cc -c program.c
		requires program.c program.h allfunctions.h
