

PORT  = 12345
HOSTS = 127.0.0.1:22222 localhost:33333

actionset1: #potato
	echo starting actionset1
	remote-cal
	# remote-lakjsdnk
	# remote-cal
	# 	requires program.c program.h allfunctions.h # potato
	# remote-cc program.c # potato

actionset2: #potato
	echo starting actionset2
	remote-cal